# Generated by Django 4.2.16 on 2026-05-24 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility / Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('label', models.CharField(help_text="Human-readable label, e.g. 'HQ Electricity Meter'", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='emissions.client')),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='ingestion_files/')),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='emissions.datasource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel')], max_length=20)),
                ('source_row_ref', models.CharField(blank=True, help_text='Original row ID/document number from source', max_length=255)),
                ('scope', models.CharField(choices=[('1', 'Scope 1'), ('2', 'Scope 2'), ('3', 'Scope 3')], max_length=1)),
                ('category', models.CharField(choices=[('fuel_diesel', 'Diesel Combustion'), ('fuel_petrol', 'Petrol/Gasoline Combustion'), ('fuel_natural_gas', 'Natural Gas Combustion'), ('fuel_lpg', 'LPG Combustion'), ('fuel_other', 'Other Fuel Combustion'), ('electricity', 'Purchased Electricity'), ('travel_air', 'Air Travel'), ('travel_hotel', 'Hotel Stay'), ('travel_ground', 'Ground Transport'), ('travel_rail', 'Rail Travel')], max_length=30)),
                ('activity_description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(help_text='Original unit from source (L, kWh, km, nights, etc.)', max_length=20)),
                ('quantity_normalized', models.DecimalField(blank=True, decimal_places=4, help_text='Normalized to SI or standard reporting unit', max_digits=18, null=True)),
                ('unit_normalized', models.CharField(blank=True, max_length=20)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, help_text='kg CO2e per unit (from DEFRA/EPA factors)', max_digits=12, null=True)),
                ('emission_factor_source', models.CharField(blank=True, default='DEFRA 2023', max_length=100)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, help_text='Calculated: quantity_normalized * emission_factor', max_digits=14, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('billing_period_start', models.DateField(blank=True, null=True)),
                ('billing_period_end', models.DateField(blank=True, null=True)),
                ('facility_code', models.CharField(blank=True, max_length=50)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('cost_center', models.CharField(blank=True, max_length=50)),
                ('origin', models.CharField(blank=True, help_text='For travel: departure location/airport code', max_length=255)),
                ('destination', models.CharField(blank=True, help_text='For travel: arrival location/airport code', max_length=255)),
                ('traveler_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged for Review'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked for Audit')], default='PENDING', max_length=20)),
                ('flag_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.client')),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.ingestionjob')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked'), ('EDITED', 'Edited'), ('UNFLAGGED', 'Unflagged')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('diff', models.JSONField(default=dict, help_text='Field-level diff for EDITED actions')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='emissions.emissionrecord')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserClientMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ANALYST', 'Analyst'), ('ADMIN', 'Admin')], default='ANALYST', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='emissions.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'client')},
            },
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['client', 'scope'], name='emissions_e_client__95b7c8_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['client', 'status'], name='emissions_e_client__a9862c_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['ingestion_job'], name='emissions_e_ingesti_c688de_idx'),
        ),
    ]
